## 1. Load the dataset
- **link :** https://www.kaggle.com/code/ibtesama/getting-started-with-a-movie-recommendation-system?select=movies_metadata.csv 
- `movie_metadata.csv`
- `rating.csv`

In [1]:
import pandas as pd

In [2]:
metadata=pd.read_csv("movies_metadata.csv")
rating=pd.read_csv("ratings.csv")

C:\Users\dhanushsr\AppData\Local\Temp\ipykernel_32616\947804907.py:1: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata=pd.read_csv("movies_metadata.csv")

In [3]:
print(metadata.columns, '\n')
print(rating.columns)

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')

In [4]:
print(metadata.info(), '\n')
print(rating.info())

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.3+ MB
None

<class 'pandas.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB
None

In [5]:
print(metadata.head(),'\n')
print(rating.head())

   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
2  A family wedding reignites the ancient feud be...  ...   1995-12-22
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4  Just when George Banks has recovered from his ...  ...   1995-02-10

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

[5 rows x 24 columns]

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

## Data Preprocessing
- We planned to merge two dataset on `metadata-id` and `ratings-movieId`
- After going through the info and summary we have found out that `metaadata-id` column is actually **tmdb_id** which is not same as `ratings-movieId`
- We explored the kaggle dataset and found a solution. There is a **link.csv** file which has mainly 3 attributes `movieId,imdbid,tmdbid`
- So we are going to make new movieId column on metadata using merge function mapping on tmbdid from `metadata` and movieId from `link`

In [6]:
link=pd.read_csv('links.csv')
link.info()

<class 'pandas.DataFrame'>
RangeIndex: 45843 entries, 0 to 45842
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  45843 non-null  int64
 1   imdbId   45843 non-null  int64
 2   tmdbId   45624 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.0 MB

##### Converting `id` from string to integer
- From the `metadata.info` we found that the `id` is in string so we need to convert it into numeric format to map the two datasets

In [7]:
metadata['id'] = pd.to_numeric(metadata['id'], errors='coerce')
metadata = metadata.dropna(subset=['id'])
metadata['id'] = metadata['id'].astype(int)

In [8]:
metadata = pd.merge(link, metadata, left_on='tmdbId', right_on='id')

In [9]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 45525 entries, 0 to 45524
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movieId                45525 non-null  int64
 1   imdbId                 45525 non-null  int64
 2   tmdbId                 45525 non-null  float64
 3   adult                  45525 non-null  str
 4   belongs_to_collection  4497 non-null   str
 5   budget                 45525 non-null  str
 6   genres                 45525 non-null  str
 7   homepage               7789 non-null   str
 8   id                     45525 non-null  int64
 9   imdb_id                45508 non-null  str
 10  original_language      45514 non-null  str
 11  original_title         45525 non-null  str
 12  overview               44571 non-null  str
 13  popularity             45522 non-null  object
 14  poster_path            45139 non-null  str
 15  production_companies   45522 non-null  str
 16  production_countries   45522 non-null  str
 17  release_date           45438 non-null  str
 18  revenue                45522 non-null  float64
 19  runtime                45265 non-null  float64
 20  spoken_languages       45522 non-null  str
 21  status                 45441 non-null  str
 22  tagline                20436 non-null  str
 23  title                  45522 non-null  str
 24  video                  45522 non-null  object
 25  vote_average           45522 non-null  float64
 26  vote_count             45522 non-null  float64
dtypes: float64(5), int64(3), object(2), str(17)
memory usage: 9.4+ MB

##### Extraction of data
- We only need the **orginal title** and **movieid** from `metadata`
- Combine with `ratings`

In [10]:
metadata = metadata[['movieId', 'original_title']]

In [11]:
data=pd.merge(rating,metadata,on='movieId')

In [12]:
data

,userId,movieId,rating,timestamp,original_title
0,1,110,1.0,1425941529,Braveheart
1,1,147,4.5,1425942435,The Basketball Diaries
2,1,858,5.0,1425941523,The Godfather
3,1,1221,5.0,1425941546,The Godfather: Part II
4,1,1246,5.0,1425941556,Dead Poets Society
...,...,...,...,...,...
25991090,270896,58559,5.0,1257031564,The Dark Knight
25991091,270896,60069,5.0,1257032032,WALL·E
25991092,270896,63082,4.5,1257031764,Slumdog Millionaire
25991093,270896,64957,4.5,1257033990,The Curious Case of Benjamin Button
25991094,270896,71878,2.0,1257031858,The Stepfather

##### Extractring  Active UserId's only
- Users who have put more than 50 ratings are taken

In [13]:
user_counts = data['userId'].value_counts()
user_counts

userId
45811     18260
8659       9251
270123     7631
179792     7513
228291     7401
          ...
270778        1
270783        1
270826        1
270853        1
270862        1
Name: count, Length: 270883, dtype: int64

In [14]:
active_users = user_counts[user_counts > 50].index
active_users

Index([ 45811,   8659, 270123, 179792, 228291, 243443,  98415, 229879,  98787,
       172224,
       ...
       269018, 269108, 269408, 269727, 269923, 270263, 270449, 270554, 270585,
       270726],
      dtype='int64', name='userId', length=102307)

In [15]:
data=data[data['userId'].isin(active_users)]

In [16]:
data

,userId,movieId,rating,timestamp,original_title
59,4,223,4.0,1042668576,Clerks
60,4,415,4.0,1042667925,Another Stakeout
61,4,648,4.0,1042674800,Mission: Impossible
62,4,1097,5.0,1042667925,E.T. the Extra-Terrestrial
63,4,1197,4.0,1042667956,The Princess Bride
...,...,...,...,...,...
25991090,270896,58559,5.0,1257031564,The Dark Knight
25991091,270896,60069,5.0,1257032032,WALL·E
25991092,270896,63082,4.5,1257031764,Slumdog Millionaire
25991093,270896,64957,4.5,1257033990,The Curious Case of Benjamin Button
25991094,270896,71878,2.0,1257031858,The Stepfather

##### Extracting Popular Movies
- Top 1500 most rated movies are taken

In [73]:
data['movieId'].value_counts()

movieId
356       64984
296       63285
318       60501
593       59601
2571      58635
          ...
63239       137
122888      124
170827      112
72591       106
5192        102
Name: count, Length: 1093, dtype: int64

In [74]:
top_movies = data['original_title'].value_counts().head(1500).index
data = data[data['original_title'].isin(top_movies)]

In [20]:
data

,userId,movieId,rating,timestamp,original_title
59,4,223,4.0,1042668576,Clerks
60,4,415,4.0,1042667925,Another Stakeout
61,4,648,4.0,1042674800,Mission: Impossible
62,4,1097,5.0,1042667925,E.T. the Extra-Terrestrial
63,4,1197,4.0,1042667956,The Princess Bride
...,...,...,...,...,...
25991090,270896,58559,5.0,1257031564,The Dark Knight
25991091,270896,60069,5.0,1257032032,WALL·E
25991092,270896,63082,4.5,1257031764,Slumdog Millionaire
25991093,270896,64957,4.5,1257033990,The Curious Case of Benjamin Button
25991094,270896,71878,2.0,1257031858,The Stepfather

## User-item Matrix
- Took a sample of 1 million.
- Created a pivot table.
-

In [54]:
data

,userId,movieId,rating,timestamp,original_title
59,4,223,4.0,1042668576,Clerks
61,4,648,4.0,1042674800,Mission: Impossible
62,4,1097,5.0,1042667925,E.T. the Extra-Terrestrial
63,4,1197,4.0,1042667956,The Princess Bride
64,4,1210,2.0,1042667865,Return of the Jedi
...,...,...,...,...,...
25991089,270896,56367,4.5,1257031529,Juno
25991090,270896,58559,5.0,1257031564,The Dark Knight
25991091,270896,60069,5.0,1257032032,WALL·E
25991092,270896,63082,4.5,1257031764,Slumdog Millionaire
25991093,270896,64957,4.5,1257033990,The Curious Case of Benjamin Button

In [55]:
user_movie_matrix = data.pivot_table(
    index='userId',
    columns='original_title',
    values='rating'
)

In [56]:
user_movie_matrix

original_title,(500) Days of Summer,10 Things I Hate About You,101 Dalmatians,12 Angry Men,2001: A Space Odyssey,21 Grams,28 Days Later,300,3:10 to Yuma,50 First Dates,...,となりのトトロ,もののけ姫,アキラ,ハウルの動く城,七人の侍,千と千尋の神隠し,卧虎藏龙,紅番區,英雄,올드보이
userId,,,,,,,,,,,,,,,,,,,,,
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270887,NaN,NaN,1.0,1.0,3.0,NaN,3.0,1.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN
270892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,NaN,NaN,NaN,NaN,1.5,NaN,NaN,NaN,1.5
270896,NaN,NaN,NaN,NaN,4.5,NaN,4.0,4.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,NaN,NaN,NaN,NaN

In [57]:
user_movie_matrix.notna().sum().sum()

np.int64(13774198)

##### Calculate cosine similarity
- Replacing `Nan` in the matrix with *0*
- Made a matrix using cosine similarity

In [63]:
from sklearn.metrics.pairwise import cosine_similarity

# Replace NaN with 0
matrix_filled = user_movie_matrix.fillna(0)

similarity = cosine_similarity(matrix_filled.T)

import pandas as pd
similarity_df = pd.DataFrame(
    similarity,
    index=user_movie_matrix.columns,
    columns=user_movie_matrix.columns
)

In [95]:
similarity_df

original_title,(500) Days of Summer,10 Things I Hate About You,101 Dalmatians,12 Angry Men,2001: A Space Odyssey,21 Grams,28 Days Later,300,3:10 to Yuma,50 First Dates,...,となりのトトロ,もののけ姫,アキラ,ハウルの動く城,七人の侍,千と千尋の神隠し,卧虎藏龙,紅番區,英雄,올드보이
original_title,,,,,,,,,,,,,,,,,,,,,
(500) Days of Summer,1.000000,0.256212,0.119652,0.200535,0.165317,0.224721,0.256206,0.306253,0.239667,0.293075,...,0.208861,0.182174,0.116361,0.234337,0.115079,0.270040,0.179380,0.039637,0.162770,0.271082
10 Things I Hate About You,0.256212,1.000000,0.242292,0.168730,0.175905,0.161469,0.231333,0.213222,0.152642,0.339637,...,0.131192,0.175309,0.138384,0.151591,0.114666,0.193982,0.254243,0.119191,0.163726,0.124169
101 Dalmatians,0.119652,0.242292,1.000000,0.142487,0.173277,0.118473,0.156935,0.156514,0.114004,0.208074,...,0.113605,0.130927,0.114226,0.122144,0.114404,0.147205,0.162700,0.141667,0.122334,0.088270
12 Angry Men,0.200535,0.168730,0.142487,1.000000,0.373809,0.212061,0.235236,0.221781,0.218932,0.161622,...,0.186691,0.215120,0.178499,0.181300,0.350782,0.264548,0.277732,0.121003,0.199597,0.264220
2001: A Space Odyssey,0.165317,0.175905,0.173277,0.373809,1.000000,0.242619,0.323592,0.246317,0.202217,0.156635,...,0.229067,0.308067,0.357831,0.221456,0.414954,0.321572,0.409405,0.197987,0.259396,0.272884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
千と千尋の神隠し,0.270040,0.193982,0.147205,0.264548,0.321572,0.229954,0.357995,0.313417,0.203064,0.200606,...,0.578763,0.590871,0.343702,0.602921,0.301830,1.000000,0.404057,0.102662,0.363363,0.384250
卧虎藏龙,0.179380,0.254243,0.162700,0.277732,0.409405,0.270167,0.357556,0.295291,0.232586,0.216341,...,0.260606,0.386119,0.320228,0.262142,0.332843,0.404057,1.000000,0.195603,0.437324,0.259778
紅番區,0.039637,0.119191,0.141667,0.121003,0.197987,0.079434,0.117582,0.077660,0.073701,0.083815,...,0.068912,0.138612,0.200663,0.059520,0.180362,0.102662,0.195603,1.000000,0.143932,0.070331
英雄,0.162770,0.163726,0.122334,0.199597,0.259396,0.273185,0.328085,0.286668,0.236084,0.192490,...,0.257132,0.336000,0.283434,0.275084,0.261254,0.363363,0.437324,0.143932,1.000000,0.298868
올드보이,0.271082,0.124169,0.088270,0.264220,0.272884,0.294719,0.356621,0.336285,0.264982,0.171294,...,0.291166,0.312246,0.249990,0.319664,0.258053,0.384250,0.259778,0.070331,0.298868,1.000000

##### Sanity Checking of recommendation system
- We used item-item collaborative filtering with cosine similarity. Movies are represented as vectors of user ratings. Similarity is computed based on user rating patterns, and recommendations are generated by averaging similarity scores across selected movies.

In [64]:
similarity_df["Toy Story"].sort_values(ascending=False).head(10)

original_title
Toy Story                  1.000000
Forrest Gump               0.628536
Star Wars                  0.623948
Toy Story 2                0.619026
Jurassic Park              0.618982
Back to the Future         0.616780
Return of the Jedi         0.601976
The Lion King              0.600687
Aladdin                    0.599716
The Empire Strikes Back    0.591793
Name: Toy Story, dtype: float64

##### Making it more user friendly
` Constructed for multiple movie inputs

In [80]:
def recommend_safe(movie_list, n=5):
    valid_movies = []
    
    for m in movie_list:
        matches = [x for x in similarity_df.columns if m.lower() in x.lower()]
        if matches:
            valid_movies.append(matches[0])

    if not valid_movies:
        return []   # ← always return list

    scores = similarity_df[valid_movies].mean(axis=1)
    scores = scores.sort_values(ascending=False)
    scores = scores.drop(valid_movies)

    return list(scores.head(n).index)

In [77]:
recommend_safe([
  "Random Unknown Movie"
])

'No valid movies found'

In [86]:
def recommend(movie_list, n=5):
    recs = recommend_safe(movie_list, n)
    print("Recommended movies:\n")
    for i, m in enumerate(recs, 1):
        print(f"{i}. {m}")

In [87]:
recommend([
  "Mission"
])

Recommended movies:

1. Hollow Man
2. Pitch Black
3. Lost in Space
4. Galaxy Quest
5. Mission: Impossible II

In [94]:
recommend(["toy",'mission'],n=10)

Recommended movies:

1. Star Wars
2. Back to the Future
3. Jurassic Park
4. Toy Story 2
5. Return of the Jedi
6. Men in Black
7. The Matrix
8. The Empire Strikes Back
9. Forrest Gump
10. Independence Day